name: ntust_ap
description: A new Flutter application.
version: 0.2.2+22

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  ap_common: 0.3.0
  #    path: ../../GitHub-NKUST-ITC/ap_common
  ap_common_firebase:
    git:
      url: https://github.com/abc873693/ap_common_firebase
      ref: v0.2.0
#      path: ../ap_common_firebase
  ap_common_plugin:
    git:
      url: https://github.com/abc873693/ap_common_plugin
      ref: v0.0.3
  #    path: ../ap_common_plugin
  http: 0.12.0+4
  dio: 3.0.9
  dio_cookie_manager: 1.0.0
  image: ^2.1.4
  html: ^0.14.0+2
  flutter_inappwebview: 4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/labels.txt
    - assets/model.tflite
